version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /njs
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /docker/md-link-check-recursive
    schedule:
      interval: daily
