version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /njs
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directory: /pip
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /docker/md-link-check-recursive
    schedule:
      interval: weekly
