name: build-and-push-docker

# only on tag push and something on "docker" dir has changed
on:
  push:
    tags: 'v*'
    paths:
      - 'docker/**'

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: caian
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run script
        run: |
          cd docker
          ./build-all.sh
